kakao:
  url: https://dapi.kakao.com/v2/search/blog
  api-key: ${kakao-secret} # Authorization
naver:
  url: https://openapi.naver.com/v1/search/blog
  client-id: ${naver-secret-id} # X-Naver-Client-Id
  client-secret: ${naver-secret} # X-Naver-Client-Secret

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true


---

spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/vacation?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: saechim
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20 # default = 10
  jpa:
    hibernate:
      ddl-auto: create-drop